apiVersion: 1

datasources:
- name: prometheusdata
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  isDefault: true
  version: 1
  editable: false
- name: jaeger
  type: jaeger
  access: proxy
  orgId: 1
  url: http://jaeger:16686
  isDefault: false
  version: 1
  editable: false